"""Shared media I/O for generation tools: persist results, resolve references.

Coordinates the byte store and the DB reference record so the tools themselves
stay focused on calling the provider.
"""

from __future__ import annotations

from app.infrastructure.media_store import to_data_uri
from app.models.media_asset import MediaKind
from app.pipeline.types.artifacts import MediaRef
from app.services.media_asset_repository import MediaAssetRepository


def reference_to_data_uri(ref: MediaRef, repo: MediaAssetRepository) -> str:
    """Hydrate a reference image into a base64 data URI for the provider request."""
    doc, data = repo.hydrate(ref.asset_id)
    return to_data_uri(data, doc.mime)


def persist_result(
    *,
    data: bytes,
    kind: MediaKind,
    mime: str,
    repo: MediaAssetRepository,
    provider: str,
    provider_request_id: str | None = None,
    prompt: str | None = None,
    width: int | None = None,
    height: int | None = None,
    duration_s: float | None = None,
    seed: int | None = None,
    source_asset_ids: list[str] | None = None,
) -> MediaRef:
    """Save generated bytes + reference record, return the handle that flows downstream."""
    doc = repo.save_bytes(
        data,
        kind=kind,
        mime=mime,
        provider=provider,
        provider_request_id=provider_request_id,
        prompt=prompt,
        width=width,
        height=height,
        duration_s=duration_s,
        seed=seed,
        source_asset_ids=source_asset_ids,
    )
    return MediaRef(
        asset_id=doc.asset_id,
        kind=doc.kind,
        mime=doc.mime,
        width=doc.width,
        height=doc.height,
        duration_s=doc.duration_s,
        provider=doc.provider,
    )
